shallow_clone: true

os:
  - Visual Studio 2015
  
platform: x64
  - x64
  
branches:
  only:
    - master

install:
  - cinst cmake
  - set PATH=C:\Program Files\CMake\bin;%PATH%
  - git init
  - git remote add origin https://github.com/hasherezade/hollows_hunter.git
  - git branch --set-upstream-to=origin/master master
  - git pull --rebase
  - git submodule update --init --recursive

build:
  verbosity: detailed

configuration:
  - Debug
  
environment:
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"

build_script:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
      cmake .. -A x64 )
  - if [%env_arch%]==[x86] (
      cmake .. )
  - cmake --build .
  - cd ..

after_build:
  - cd build
  - cp pe-sieve\Debug\pe-sieve.dll Debug\
  - cd ..
 
test_script:
  - cd build
  - ctest -V
